[package]
name = "eye_guard"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.29"
egui = "0.24"
egui-winit = "0.24"
notify-rust = "4.10.0"
tokio = { version = "1", features = ["full"] }
pixels = "0.13"
