[package]
name = "eye_guard"
version = "0.1.0"
edition = "2024"

[dependencies]
pixels = "0.13"
winit = { version = "0.29", features = ["wayland", "x11", "run-return"] }
notify-rust = "4"
tokio = { version = "1", features = ["full"] }
